### ISSUE TITLE
Commented Out Code???

### ISSUE THREAD

**Issue by richgurney** [redemptive/testing-cookbook#1]
**Do we need this commented out code**

# remote_file '/tmp/nodesource_setup.sh' do
# 	source  'http://deb.nodesource.com/setup_6.x'
# 	action  :create
# end

# execute 'update node resources' do
# 	command 'sh /tmp/nodesource_setup.sh'
# end

# package 'nodejs' do
# 	action :upgrade

**Comment by redemptive** [comment]
This task was completed
